#!/bin/bash
set -e

if [[ -z "${SHIBBOLETH_SP_ENTITY_ID}" ]]; then
  # disable mod_shib
  a2dismod shib
  rm /etc/apache2/conf-enabled/shib.conf /etc/apache2/conf-enabled/moodle-shib.conf
else
  export SHIBD_SERVICE_IP=`getent hosts ${SHIBD_SERVICE_NAME} | awk '{ print $1  }'`

  envsubst < /etc/shibboleth/shibboleth2.xml-template > /etc/shibboleth/shibboleth2.xml
  chmod 644 /etc/shibboleth/shibboleth2.xml
fi
